version: '3'
services: 
    db:
        container_name: db
        image: 'mysql:latest'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    # app:
    #     container_name: node-typeorm
    #     restart: always
    #     build: .
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         - db
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-node-typeorm
        environment:
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            PMA_HOST: db
        restart: always
        depends_on:
            - db
        links:
            - db

        ports:
            - "9191:80"  
